# Generated by Django 5.0 on 2023-12-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=255)),
                ('book_genre', models.CharField(default='Others', max_length=255)),
                ('book_image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('book_price', models.IntegerField()),
                ('book_publisher', models.CharField(max_length=255)),
                ('book_publication_date', models.DateField()),
                ('book_content', models.TextField()),
                ('book_likes', models.IntegerField(default=0)),
                ('book_isbn', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_name', models.CharField(max_length=255)),
                ('voice_like', models.IntegerField(default=0)),
                ('voice_path', models.CharField(max_length=255)),
                ('voice_image_path', models.CharField(max_length=255)),
                ('voice_created_date', models.DateTimeField(auto_now_add=True)),
                ('voice_is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
