# Generated by Django 5.0 on 2023-12-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audiobook", "0002_book_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_content",
            field=models.CharField(max_length=255),
        ),
    ]
