# Generated by Django 5.0 on 2023-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0002_book_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_content',
            new_name='book_content_path',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image_path',
            field=models.TextField(),
        ),
    ]
