# Generated by Django 5.0 on 2023-12-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0003_rename_book_content_book_book_content_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_content_path',
            field=models.FileField(upload_to='book_contents/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image_path',
            field=models.ImageField(upload_to='book_images/'),
        ),
    ]
