# Generated by Django 5.0 on 2023-12-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audiobook", "0003_alter_book_book_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_content",
        ),
        migrations.AddField(
            model_name="book",
            name="book_content_path",
            field=models.TextField(default="empty"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="book_image_path",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voice",
            name="voice_image_path",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voice",
            name="voice_path",
            field=models.TextField(),
        ),
    ]
