# Generated by Django 5.0 on 2023-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0004_alter_book_book_content_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_price',
        ),
    ]
