# Generated by Django 5.0 on 2023-12-21 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audiobook", "0004_remove_book_book_content_book_book_content_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voice",
            name="voice_created_date",
        ),
    ]
