# Generated by Django 5.0 on 2023-12-21 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audiobook", "0005_remove_voice_voice_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="voice_created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
