# Generated by Django 5.0 on 2023-12-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0005_remove_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_content_path',
            field=models.FileField(null=True, upload_to='book_contents/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image_path',
            field=models.ImageField(blank=True, upload_to='book_images/'),
        ),
    ]
