# Generated by Django 5.0 on 2023-12-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_phone_number',
        ),
    ]
