# Generated by Django 5.0 on 2023-12-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_phone_number',
        ),
    ]
