# Generated by Django 5.0 on 2023-12-22 04:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_book_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
